### ISSUE TITLE
start server error

### ISSUE THREAD

**Issue by stechu** [Ptival/PeaCoq#2]
It happens after I pull the current master.

![screenshot 2015-01-12 11 59 05](https://cloud.githubusercontent.com/assets/720571/5709898/7f58a6e0-9a52-11e4-9923-2e7d806e983c.png)

**Comment by Ptival** [comment]
Can you run

```
./setup.sh
```

**Comment by stechu** [comment]
Yes, is there any assumption on installation folder or log folder?
got the error below.
![screenshot 2015-01-12 12 31 06](https://cloud.githubusercontent.com/assets/720571/5710442/eb090e30-9a56-11e4-9a2a-7c3287ac1e56.png)

**Comment by Ptival** [comment]
Ah, you must have an old version of my config file. Could you please post
the contents of the file ~/.PeaCoqConfig.hs

What will probably solve the problem is deleting said file and running
setup.sh again. Sorry about this, you can ssh to attu or a cycle machine if
you want to avoid the trouble... ;-)

**Comment by stechu** [comment]
@Ptival  It works!
Thanks a lot!

**Comment by Callejn** [comment]
Hi, I just thought that I should point out that this happened to me today; I cloned the repo, I ran setup.hs and cabal install, got the above error message. I then altered start-peacoq.hs (don't know if this matters; what I changed was basically the definition of ZACKHOME to be echo ~ instead of what was there before). I deleted ~/.PeaCoqConfig.hs and ran setup.hs and cabal install again, and it worked.

**Comment by Ptival** [comment]
@Callejn Oh, thanks! There must be leftovers from a user study run at UW, I will try to fix this ASAP.

**Comment by Ptival** [comment]
@Callejn Actually, the start-peacoq.sh and stop-peacoq.sh were here to help students, but if you use PeaCoq personally, you can start it by:

```
cabal install
peacoq -p <PORT>
```

No need to use the shell scripts.

**Comment by Callejn** [comment]
@Ptival, ok, I wasn't sure if it mattered or not, just thought that I should mention it. I did get it working after I deleted ~/.PeaCoqConfig.hs and ran setup.hs again (and I must say that it seems very nice, by the way!).

But I found it strange that I did get the wrong ~/.PeaCoqConfig.hs the first time but not the second time. Maybe something in the setup is done in wrong order, making the config file default to something? It can also be that I had some trouble when running cabal install the first time (I could not install all the dependencies the first time).
