### ISSUE TITLE
Unsupported unicode character:0x200b

### ISSUE THREAD

**Issue by tbelaire** [Ptival/PeaCoq#29]
HI, I was trying to try this out, and after I tried to navigate back to the editor pane to do an `exact H`, things got a little weird.  I still could complete the proof, but afterwards I got the error

```
Syntax Error: Lexer: Unsupported Unicode character (0x200b)
```

I think it went wrong at line 629 in this file.
https://gist.github.com/21a092c40970aa2cde1e

**Comment by Ptival** [comment]
Hi Theo,

This must have happened because of the way the old PeaCoq managed to separate the different parts of the buffer, using an invisible separating character. Sometimes, a hiccup results in the invisible character staying in the buffer somewhere.

I am most likely not going to fix this as I am working on the new version which does not use the same hack.

If this happens, try moving your cursor left and right to find where the invisible character is, and delete it. Sorry for the inconvenience.
