### ISSUE TITLE
setup for Test.hs

### ISSUE THREAD

**Issue by tbelaire** [Ptival/PeaCoq#32]
What's required to build the ml modules and install them so that `Test.hs` works?

**Comment by Ptival** [comment]
Right now `Test.hs` will only work on my machine, because I hardcoded the coqtop path.

You can replace the coqtop line to only contain:

```
coqtop = "/path/to/coqtop -ideslave -main-channel stdfds"
```

As long as you don't use the `addGoalContext` function and remove the lines in `main` that are PeaCoq-specific. That way you can interact with coqtop using the XML protocol.

If you actually want to use the `PeaCoqGetContext.` plugin command, then you need to keep the `-I` and `-Q` in the `coqtop` invocation, and you need to build the plugin first.

Right now, the way to build the plugin is to go in the plugin folder and run `make`. If you are under NixOS, you can `nix-shell --run make` to have the proper OCaml/Coq.

At the moment I think there are discrepancies between all of this, I'm going to fix it real soon so that you can build everything from the root folder.

Let me know if you have further questions. Sorry, it's a bit of a mess right now, trying to make it releasable! :)

**Comment by tbelaire** [comment]
Alright, sounds good.

**Comment by tbelaire** [comment]
Cool, it works okay now.

https://github.com/tbelaire/PeaCoq/blob/Coq-Annotator/src/Coq-Annotate.hs

```
Theorem n_plus_z : forall n, n + 0 = n.

(*context

====================
forall n : nat, n + 0 = n

*)

Proof.

(*context

====================
forall n : nat, n + 0 = n

*)

    intros n.

(*context

n : nat
====================
n + 0 = n

*)

    induction n.

(*context

====================
0 + 0 = 0


n : nat
IHn : n + 0 = n
====================
S n + 0 = S n

*)

    reflexivity.

(*context

n : nat
IHn : n + 0 = n
====================
S n + 0 = S n

*)

```

**Comment by tbelaire** [comment]
It's pretty much working now.  I can route my example file though the whole system and get an html file which works.

**Comment by Ptival** [comment]
Great news!

Let me know if there's any code change that would make things simpler to use.

**Comment by tbelaire** [comment]
It would be nice to build this as a library, so I can just depend on it in a separate cabal project.  And I didn't want to make that change on my own, as it's kinda architectural.

**Comment by tbelaire** [comment]
In particular, I think that PeaCoq, Sessions, Handlers and so on make sense as a separate executable listing from the rest of the coqtop communication library.

Something like this: 
http://stackoverflow.com/questions/12305970/how-to-make-a-haskell-cabal-project-with-libraryexecutables-that-still-run-with

might be  good.

Next on things I need to do is port coq-lit.py into Haskell and generate things directly I think.
I kinda want to just use Pygments to do syntax highlighting as well, but that wants to take in coq and spit out html, while I also want to do that, so I'll need to figure out how to merge/chain the tools.
