### ISSUE TITLE
Being able to go back and forth between the text mode of a proof and the proof tree

### ISSUE THREAD

**Issue by emackay** [Ptival/PeaCoq#8]
It would be extremely useful if we could go back and forth between entering the tactics of a proof as text and the proof tree, because I often don't know what tactics make sense in this context, or I may just want a little nudge in the right direction, so being able to have the proof tree incorporate as much of the proof as we have filled in and then go on from there would be great. And after filling some portions in with the proof tree, going back to text mode would be good too. Maybe an option to just put the proof tree contents in comments like it is now, or to fill in things in the body of the proof as if we had done it all in text mode.

**Comment by Ptival** [comment]
Hey Eric,

Obviously this is something I would love too! :)

It turns out it is subtle in the way PeaCoq is working right now. But there is hope, as I have changed PeaCoq quite a lot over the past few weeks and removed some of the barriers that made this challenging.

The current problem is that there is no bijection between PeaCoq's state and the editor buffer state, because PeaCoq processes things in a weird way, for legacy reasons. I plan to change it, as it becomes an important problem now that we use existential variables.

More on this subject soon...

**Comment by Ptival** [comment]
Fixed in branches seamless and codemirror.
